/**
 * Regenerate src/components/README.md, the inventory AGENTS.md tells every
 * contributor to read before writing a new component.
 *
 * It parses exports rather than tracking them by hand, because an inventory that
 * has to be updated manually is one that silently goes stale and then stops
 * being trusted.
 *
 * Run with `pnpm components:list`.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = 'src/components';

/** Every .ts/.tsx file under a directory, excluding barrels and tests. */
function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
      continue;
    }
    if (!/\.tsx?$/.test(entry)) continue;
    if (/\.(test|spec|stories)\.tsx?$/.test(entry)) continue;
    // Barrels only re-export names already attributed to their source file.
    if (/^index\.tsx?$/.test(entry)) continue;
    out.push(full);
  }
  return out;
}

/**
 * Exported names, ignoring types. A component is capitalised; a hook starts with
 * `use`. Anything else is a helper and is listed too, since composing one is
 * still preferable to writing a second copy.
 */
function exportsOf(source) {
  const names = new Set();

  // export function Foo / export const Foo = / export class Foo,
  // and the `export default function Foo` form the snippets use.
  for (const m of source.matchAll(
    /^export\s+(?:default\s+)?(?:async\s+)?(?:function|const|class)\s+([A-Za-z_$][\w$]*)/gm
  )) {
    names.add(m[1]);
  }
  // export { A, B as C }
  for (const m of source.matchAll(/^export\s*\{([^}]*)\}/gm)) {
    for (const part of m[1].split(',')) {
      const cleaned = part.trim();
      if (!cleaned || cleaned.startsWith('type ')) continue;
      const alias = cleaned
        .split(/\s+as\s+/)
        .pop()
        .trim();
      if (alias) names.add(alias);
    }
  }

  return [...names].filter((n) => /^[A-Z]/.test(n) || /^use[A-Z]/.test(n));
}

const files = walk(ROOT).sort();

/** Group by the directory immediately under src/components. */
const groups = new Map();
for (const file of files) {
  const rel = relative(ROOT, file);
  const group = rel.split(sep)[0].replace(/\.tsx?$/, '');
  const names = exportsOf(readFileSync(file, 'utf8'));
  if (names.length < 1) continue;
  if (!groups.has(group)) groups.set(group, []);
  groups.get(group).push({ path: rel.split(sep).join('/'), names });
}

let total = 0;
for (const entries of groups.values()) for (const e of entries) total += e.names.length;

const lines = [
  '# Component inventory',
  '',
  '<!-- Generated by `pnpm components:list`. Do not edit by hand. -->',
  '',
  `${total} exports across ${groups.size} groups.`,
  '',
  'Read this before writing a new component. If something here already does the job,',
  'compose it. If it nearly does, compose it and pass a `className` rather than forking',
  'it. See the "build the UI from atoms upward" rule in AGENTS.md.',
  ''
];

for (const group of [...groups.keys()].sort()) {
  lines.push(`## ${group}`, '');
  lines.push('| File | Exports |', '| ---- | ------- |');
  for (const { path, names } of groups.get(group).sort((a, b) => a.path.localeCompare(b.path))) {
    lines.push(`| \`${path}\` | ${names.map((n) => `\`${n}\``).join(', ')} |`);
  }
  lines.push('');
}

writeFileSync(join(ROOT, 'README.md'), lines.join('\n'));
console.log(`Wrote ${ROOT}/README.md: ${total} exports across ${groups.size} groups.`);
