#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

REMOVE="rm -rf public/sw.js public/sw.js.map public/workbox-*.js public/workbox-*.js.map .next"
# remove files from previous builds
eval $REMOVE

# lint and build
pnpm run lint

# lint and fix
pnpm run lint:fix

# format code
pnpm run format

# run build and test for truthy
pnpm run build
# test for last command executed
if [ $? -eq 0 ]; then
  # remove build files
  eval $REMOVE
  echo -n "Build Successful 😆!"
  exit 0

  else
    echo "Oops! Build failed 😢."
    exit 130
fi
