name: Build website

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey: |
            AUTH_SPOTIFY_ID=${{ secrets.AUTH_SPOTIFY_ID }}
            AUTH_SPOTIFY_SECRET=${{ secrets.AUTH_SPOTIFY_SECRET }}
            AUTH_SPOTIFY_REFRESH_TOKEN=${{ secrets.AUTH_SPOTIFY_REFRESH_TOKEN }}
          file_name: .env

      - name: Verify envfile
        run: |
          echo "Verifying .env file content"
          diff .env <(printf "AUTH_SPOTIFY_ID=${{ secrets.AUTH_SPOTIFY_ID }}\nAUTH_SPOTIFY_SECRET=${{ secrets.AUTH_SPOTIFY_SECRET }}\nAUTH_SPOTIFY_REFRESH_TOKEN=${{ secrets.AUTH_SPOTIFY_REFRESH_TOKEN }}") || (echo "Environment variables mismatch" && exit 1)

      - name: Build project
        run: pnpm run build
